global:
  resolve_timeout: 5m

route:
  receiver: 'webhook'
  group_wait: 30s
  group_interval: 5m  
  repeat_interval: 4h
  routes:
  - receiver: webhook

receivers:
- name: webhook
  webhook_configs:
    - url: http://localhost:1337/alerts


