# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 30s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: 
    - 'localhost:9090'
    - 'localhost:1337'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "0.0.0.0:9093"
